### ISSUE TITLE
Problemas con version de la biblioteca python-telegram-bot

### ISSUE THREAD

**Issue by FuegoDomato** [comcomUBA/dcubabot#75]
El bot no funciona con la version mas nueva de python-telegram-bot (actualmente es la 20.7). Cambiaron de nombre a varias funciones y clases. Me dio paja fijarme cuales son los nombres nuevos de la biblioteca. Probe bajarme una version vieja (la 13.4) y funciona perfecto. Propongo ver que version tiene descargada la compu donde se esta ejecutando el bot y modificar el archivo requirements.txt.

**Comment by franciscod** [comment]
Probá con esto (y si anda por favor PR!):

```
APScheduler==3.6.3
beautifulsoup4==4.11.1
black==22.3.0
cachetools==4.2.2
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
click==8.1.3
cryptography==36.0.2
DateTime==4.4
future==0.18.2
httplib2==0.20.4
icalendar==4.0.9
icalevents==0.1.25
idna==3.3
mypy-extensions==0.4.3
pathspec==0.9.0
platformdirs==2.5.2
pony==0.7.16
pycparser==2.21
pyparsing==3.0.8
python-dateutil==2.8.2
python-telegram-bot==13.11
pytz==2022.1
pytz-deprecation-shim==0.1.0.post0
requests==2.27.1
robobrowser==0.5.3
six==1.16.0
soupsieve==2.3.2
tomli==2.0.1
tornado==6.1
tzdata==2022.1
tzlocal==4.2
urllib3==1.26.9
Werkzeug==0.10.4
zope.interface==5.4.0
```

**Comment by FuegoDomato** [comment]
Probe como decias. Primero me tiro este error
```
~/.local/lib/python3.11/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
```
Actualice requests a la ultima version (2.31.0)

Ahi el problema paso a ser la version de pony con el error

```
[2024-01-29 21:35:01,197] - [DCUBABOT] - [CRITICAL] - ERROR AL INICIAR EL DCUBABOT
[2024-01-29 21:35:01,197] - [DCUBABOT] - [ERROR] - Unsupported operation: RETURN_GENERATOR
Traceback (most recent call last):
  File "<PATH>/dcubabot.py", line 568, in main
    add_all_handlers(dispatcher)
  File "<PATH>/dcubabot.py", line 402, in add_all_handlers
    for command in select(c for c in Command):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pony/orm/core.py", line 5560, in select
    return make_query(args, frame_depth=cut_traceback_depth+1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pony/orm/core.py", line 5546, in make_query
    tree, external_names, cells = decompile(gen)
                                  ^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pony/orm/decompiling.py", line 38, in decompile
    decompiler = Decompiler(codeobject)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pony/orm/decompiling.py", line 156, in __init__
    decompiler.decompile()
  File "~/.local/lib/python3.11/site-packages/pony/orm/decompiling.py", line 256, in decompile
    throw(DecompileError('Unsupported operation: %s' % opname))
  File "~/.local/lib/python3.11/site-packages/pony/utils/utils.py", line 99, in throw
    raise exc
pony.orm.decompiling.DecompileError: Unsupported operation: RETURN_GENERATOR
```

Actualice pony a la version mas nueva (0.7.17) con lo que funciono perfecto.

No veo porqué agregar la precision en todas las versiones de biblioteca, mi idea era solo agregar la version del telegram bot.

De todas formas con las modificaciones el request.txt quedaria
```
APScheduler==3.6.3
beautifulsoup4==4.11.1
black==22.3.0
cachetools==4.2.2
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
click==8.1.3
cryptography==36.0.2
DateTime==4.4
future==0.18.2
httplib2==0.20.4
icalendar==4.0.9
icalevents==0.1.25
idna==3.3
mypy-extensions==0.4.3
pathspec==0.9.0
platformdirs==2.5.2
pony==0.7.17
pycparser==2.21
pyparsing==3.0.8
python-dateutil==2.8.2
python-telegram-bot==13.11
pytz==2022.1
pytz-deprecation-shim==0.1.0.post0
requests==2.31.0
robobrowser==0.5.3
six==1.16.0
soupsieve==2.3.2
tomli==2.0.1
tornado==6.1
tzdata==2022.1
tzlocal==4.2
urllib3==1.26.9
Werkzeug==0.10.4
zope.interface==5.4.0
```
Ahi hago el PR

**Comment by franciscod** [comment]
Pinea lo que consideres necesario, nada mas ni nada menos! La idea es
mejorar lo de ahora que esta re subespecificado y no anda, je. Gracias!
